import Head from 'next/head';
import { NextPage } from 'next';
import VolunteerApplicationPage from '@/components/volunteerApplicationPage/VolunteerApplicationPage';


const Application: NextPage = () => {
  return (
    <>
     <Head>
        <title>Krik Volunteers Application</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/krik-logo 1.png" />
      </Head>
      <VolunteerApplicationPage />
    </>
  )
}

export default Application

