import Head from 'next/head';
import { GetServerSideProps, NextPage } from 'next';
import VolunteersHeader from '@/components/volunteersHeader/VolunteersHeader';
import { VolunteerCardsType } from '@/interfaces';
import VolunteersCards from '@/components/volunteersCards/VolunteersCards';

interface Props {
  dataVolunteers: VolunteerCardsType
}


const Volunteers: NextPage<Props> = ({dataVolunteers}) => {
  return (
    <>
     <Head>
        <title>Krik Volunteers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/krik-logo 1.png" />
      </Head>
        <VolunteersHeader />
        <VolunteersCards data={dataVolunteers}/>
    </>
  )
}

export default Volunteers



export const getServerSideProps: GetServerSideProps = async () => {

    const resVolunteers = await fetch("http://localhost:5001/volunteers");
    const dataVolunteers: VolunteerCardsType = await resVolunteers.json();
  
  
    return {
      props: {
        dataVolunteers
      },
    };
  };