import Head from 'next/head';
import { NextPage } from 'next';
import OurTeamCarousel from '@/components/ourTeamCarousel/OurTeamCarousel';


const OurTeam: NextPage = () => {
  return (
    <>
     <Head>
        <title>Krik Our Team</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/krik-logo 1.png" />
      </Head>
      <OurTeamCarousel />
    </>
  )
}

export default OurTeam

