import Head from 'next/head';
import { GetServerSideProps, NextPage } from 'next';
import AboutUsBanner from '@/components/aboutUsBanner/AboutUsBanner';
import AboutKrik from '@/components/aboutKrik/AboutKrik';
import AboutUsFAQ from '@/components/aboutUsFAQ/AboutUsFAQ';
import { AboutUsFAQType } from '@/interfaces';

interface Props{
  dataFAQ: AboutUsFAQType
}

const AboutUs: NextPage<Props> = ({dataFAQ}) => {
  return (
    <>
     <Head>
        <title>Krik About Us</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/krik-logo 1.png" />
      </Head>
        <AboutUsBanner />
        <AboutKrik />
        <AboutUsFAQ data={dataFAQ}/>
    </>
  )
}

export default AboutUs



export const getServerSideProps: GetServerSideProps = async () => {

  const resFAQ = await fetch("http://localhost:5001/aboutUsFAQ");
  const dataFAQ: AboutUsFAQType = await resFAQ.json();


  return {
    props: {
      dataFAQ
    },
  };
};