import Head from 'next/head';
import { NextPage } from 'next';
import DonateHeader from '@/components/donateHeader/DonateHeader';
import DonateForm from '@/components/donateForm/DonateForm';


const Donate: NextPage = () => {
  return (
    <>
     <Head>
        <title>Krik Donate</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/krik-logo 1.png" />
      </Head>

      <DonateHeader />
      <DonateForm />

    </>
  )
}

export default Donate
