import Head from 'next/head';
import { Inter } from 'next/font/google';
import { GetServerSideProps, NextPage } from 'next';
import { EventCardProps, NewsCard } from '@/interfaces';
import Banner from '@/components/banner/Banner';
import EventCard from '@/components/eventCard/EventCard';
import InfoDiv from '@/components/infoDiv/InfoDiv';
import VideoDiv from '@/components/videoDiv/VideoDiv';
import News from '@/components/news/News';
import OurServices from '@/components/ourServices/OurServices';
import Partners from '@/components/partners/Partners';


const inter = Inter({ subsets: ['latin'] })

interface Props {
  dataEvent: EventCardProps,
  dataNewsCards: {
    mk: NewsCard[],
    en: NewsCard[]
  }
}

const Home: NextPage<Props> = ({ dataEvent, dataNewsCards}) => {
  return (
    <>
      <Head>
        <title>Krik</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/krik-logo 1.png" />
      </Head>
      
      <Banner/>
      <EventCard data={dataEvent}/>
      <InfoDiv />
      <VideoDiv />
      <News data={dataNewsCards} page="newsDiv"/>
      <OurServices />
      <Partners />
    </>
  )
}

export default Home

export const getServerSideProps: GetServerSideProps = async () => {

  const resEventCard = await fetch("http://localhost:5001/eventCard");
  const dataEvent: EventCardProps = await resEventCard.json();

  const resNewsCards = await fetch("http://localhost:5001/news");
  const dataNewsCards: NewsCard[] = await resNewsCards.json();

  return {
    props: {
      dataEvent,
      dataNewsCards
    },
  };
};