import Head from 'next/head';
import { NextPage } from 'next';
import ServicesPage from '@/components/servicesPage/ServicesPage';


const Services: NextPage = () => {
  return (
    <>
     <Head>
        <title>Krik Services</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/krik-logo 1.png" />
      </Head>
      <ServicesPage />
    </>
  )
}

export default Services


